### ISSUE TITLE
ISBN in the URL is messing things up.

### ISSUE THREAD

**Issue by scotdalton** [team-umlaut/umlaut-primo#1] opened 2013-05-01 19:34 UTC
https://getit.library.nyu.edu/go/7482824?umlaut.institution=NS

**Comment by jrochkind** [comment] 2013-05-02 13:58
Can you expand, messing things up how? I don't see anything obviously messed up when following that link you included, it seems to be working to me. 

I think you are running an umlaut off git there, not an official gem release? Can you give the git SHA fingerprint of the umlaut you are running where you observed the error?

Next step, if you felt like it and it was feasible, would be a failing test case of some kind.

**Comment by scotdalton** [comment] 2013-05-02 15:03
Right, messing things up by truncating the OpenURL and either losing information or making a URL that Apache (as currently configured) craps out on. Will investigate incorporating a failing test.

**Comment by jrochkind** [comment] 2013-05-02 15:19
I don't understand -- this is the same issue that you reported seperately as maximum length issues? It's reported here as ISBN, and a seperate ticket.   

But you're saying an ISBN in the URL is causing an OpenURL to be truncated?  

Is that reproducing with the URL you included above, I'm just missing how?

I am REALLY confused about what you are reporting here. You don't need a test case, but if you can describe the problem in a way I can reproduce it, or just understand what you're talking about, I am happy to look into it.

**Comment by scotdalton** [comment] 2013-05-02 15:30
OH, sorry. Wrong issue.  My bad.  Will delete my previous comment.  Very sorry.

**Comment by scotdalton** [comment] 2013-05-02 15:31
This is specific to umlaut-primo, so I just need to investigate.  Tried to get a failing test but couldn't.

**Comment by jrochkind** [comment] 2013-05-02 15:39
okay, cool, since it's specific to umlaut-primo, I'll assign to you and stop worrying about it. :) Feel free to ping me if you assistance though.

**Comment by jrochkind** [comment] 2013-05-02 15:40
Oh geez, I see this was in the issue tracker for umalut-primo from the start! I'M sorry for not noticing that and getting confused!

**Comment by scotdalton** [comment] 2013-05-02 20:16
Closing. Just a mess of confusion.  Couldn't get a test to fail, but put in [this fix](/team-umlaut/umlaut-primo/commit/89a380e532ac06431677ad529a55ee09a02e9939) which is way too  complicated and needs to be cleaned up, but seems to work.

**Closed as completed** 2013-05-02 20:17 UTC

**Comment by jrochkind** [comment] 2013-05-02 20:28
If it's any consolation, going from an OpenURL citation to the optimal search of the catalog... is a mess for me too, in my code.  I think it is inherently a mess, and ends up needing to be customized not only for the capabilities of the particular catalog software you are searching, but also for your particular data, what sorts of data you have and how your institution controls it.
